server:
  port: 9001

spring:
  application:
    name: Module1
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.66:3306/SpringBoot_SpringSecurity_AdminLTE?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.197:8848
  thymeleaf:
    cache: false
  mvc: 
     hiddenmethod:
       filter:
         enabled: true
#  mvc:
#    date-format: yyyy/MM/dd


logging:
  level:
    com.iosoft2020: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml
mybatis:
  type-aliases-package: com.iosoft2020.entity
  mapper-locations: classpath:/mapper/**/*.xml