server:
  port: 9002

spring:
  application:
    name: Module2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.197:8848
  thymeleaf:
    cache: false

logging:
  level:
    com.iosoft2020.Module2: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
